Substitute calls to convertMarkdownToHtml to MarkdownRenderer.render
Papyrus-doc-ai/papyrus-obsidian pull request #43
Opened 2024-11-10 20:11 UTC by EdBarrancos

2024-11-24 12:35 UTC, dsa-ferreira requested changes

2024-11-24 12:35 UTC, dsa-ferreira commented on src/formater/exporter.modal.ts
> +		MarkdownRenderer.render(this.app, this.template, taskListRender, "./", this.component);
Este component é o plugin em si, ou é impressão minha? não dava para o componente ser só o modal?

2024-11-24 12:35 UTC, dsa-ferreira commented on src/taskifier/taskfier.command.ts
> +	private app: App;
isto está com 2 tabs ou é impressão minha?

2024-11-24 12:35 UTC, dsa-ferreira commented on src/taskifier/taskfier.command.ts
> +	private app: App;
bem, montes de ficheiros parecem estar com 8 spaces tabs em vez de 4

2024-12-01 19:24 UTC, EdBarrancos commented on src/formater/exporter.modal.ts
> +		MarkdownRenderer.render(this.app, this.template, taskListRender, "./", this.component);
Acho que nao. Que o Modal nao da inherit do tipo Component

2024-12-01 19:29 UTC, EdBarrancos commented on src/formater/exporter.modal.ts
> +		MarkdownRenderer.render(this.app, this.template, taskListRender, "./", this.component);
Modal implementa a interface `ClosableComponent`, mas nao é um `Component` pelo que percebi

2024-12-01 19:35 UTC, EdBarrancos commented on src/taskifier/taskfier.command.ts
> +	private app: App;
Acho que so tem 1 tab. E acho que sao 4 spaces

2024-12-11 11:16 UTC, dsa-ferreira submitted a review, later dismissed

2025-01-05 16:05 UTC, merged